# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# MB.py
# Created on: 2023-11-21 09:27:19.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
KRBRoads = "KRBRoads"
KRBRoads_Layer = "KRBRoads_Layer"
KRBRoads_Layer__2_ = KRBRoads_Layer
KRBRoads_Layer__3_ = KRBRoads_Layer__2_
KRBRoads_Statistics = "C:\\Users\\Dell\\Documents\\ArcGIS\\Default.gdb\\KRBRoads_Statistics"

# Process: Make Feature Layer
arcpy.MakeFeatureLayer_management(KRBRoads, KRBRoads_Layer, "", "", "FID FID VISIBLE NONE;Shape Shape VISIBLE NONE;RID RID VISIBLE NONE;RdName RdName VISIBLE NONE;SurfType SurfType VISIBLE NONE;SurfCond SurfCond VISIBLE NONE;Road_Usage Road_Usage VISIBLE NONE;ROADCLASS ROADCLASS VISIBLE NONE;OLD_CLASS OLD_CLASS VISIBLE NONE")

# Process: Add Field
arcpy.AddField_management(KRBRoads_Layer, "Length_KM", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
arcpy.CalculateField_management(KRBRoads_Layer__2_, "Length_KM", " $length / 1000", "VB", "")

# Process: Summary Statistics
arcpy.Statistics_analysis(KRBRoads_Layer__3_, KRBRoads_Statistics, "Length_KM SUM", "SurfType")

